
print("   .:'.")
print("  :::  :")
print("   ':.'")
print("             \\")
print("            ,)\\")
print("               \\,sSss")
print("                ')ssssS")
print("                  \_sSSsSs ")
print("                  _) ssSsss ")
print("                 /   s s s ")
print("                / .'   ( ")
print("           ____/ / \.   \ ")
print("          {,----'    )   \ ")
print("                    /    ))")
print("                   /  .-'  \ ")
print("                  / .'  '.  \ ")
print("                 ( <      '. ',--._ ")
print("                  \ \       '-----.( ")
print("                   \ |            )/ ")
print("                    \;            ' " )                        
print("             snd  L/ ")

